include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - avoid_function_literals_in_foreach_calls

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "**.graphql.dart"