name: cqrs_sembast
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_toggle_tab: ^1.4.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  sembast: ^3.5.0+1
  sembast_web: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
